name: Python CI/CD Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: python -m unittest discover

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Another Branch
      run: |
        git config user.name "cresolindiateam"
        git config user.email "nitesh@cresol.in"
    - name: Deploy to Another Branch
      run: |
        git checkout -b deployment-branch
        git push origin deployment-branch
      env:
        GITHUB_TOKEN: ${{ secrets.CICD }}   
